const additionalIngredients = [
  // More Harinas y Almidones
  {
    id: 'harina-almendra-004',
    createdAt: new Date('2024-11-04T01:34:12.149Z'),
    updatedAt: new Date('2024-11-04T01:51:12.733Z'),
    name: 'Harina de Almendra',
    description: 'Harina de almendra finamente molida',
    category: 'Harinas y Almidones',
    usedInRecipes: [],
    isResaleProduct: false,
    costPerUnit: 45,
    currency: 'COP',
    currentStock: 10,
    unit: 'g',
    suppliers: [{
      name: 'Frutos Secos Premium',
      contact: '3155484856',
      address: 'Calle 45 #12-34',
    }],
    storageTemp: 'Ambiente',
    isActive: true,
    isDiscontinued: false,
    customAttributes: {},
  },
  {
    id: 'harina-avena-005',
    createdAt: new Date('2024-11-04T01:34:12.149Z'),
    updatedAt: new Date('2024-11-04T01:51:12.733Z'),
    name: 'Harina de Avena',
    description: 'Avena molida fina',
    category: 'Harinas y Almidones',
    usedInRecipes: [],
    isResaleProduct: false,
    costPerUnit: 20,
    currency: 'COP',
    currentStock: 15,
    unit: 'g',
    suppliers: [{
      name: 'Cereales del Valle',
      contact: '3155484857',
      address: 'Av 23 #45-67',
    }],
    storageTemp: 'Ambiente',
    isActive: true,
    isDiscontinued: false,
    customAttributes: {},
  },

  // More Lácteos y Proteínas
  {
    id: 'crema-leche-004',
    createdAt: new Date('2024-11-04T01:34:12.149Z'),
    updatedAt: new Date('2024-11-04T01:51:12.733Z'),
    name: 'Crema de Leche',
    description: 'Crema de leche 35% grasa',
    category: 'Lácteos y Proteínas',
    usedInRecipes: [],
    isResaleProduct: false,
    costPerUnit: 12,
    currency: 'COP',
    currentStock: 20,
    unit: 'ml',
    suppliers: [{
      name: 'Lácteos Premium',
      contact: '3155484858',
      address: 'Cra 67 #89-12',
    }],
    storageTemp: 'Refrigeracion',
    isActive: true,
    isDiscontinued: false,
    customAttributes: {},
  },
  {
    id: 'queso-crema-005',
    createdAt: new Date('2024-11-04T01:34:12.149Z'),
    updatedAt: new Date('2024-11-04T01:51:12.733Z'),
    name: 'Queso Crema',
    description: 'Queso crema para repostería',
    category: 'Lácteos y Proteínas',
    usedInRecipes: [],
    isResaleProduct: false,
    costPerUnit: 25,
    currency: 'COP',
    currentStock: 15,
    unit: 'g',
    suppliers: [{
      name: 'Lácteos Premium',
      contact: '3155484858',
      address: 'Cra 67 #89-12',
    }],
    storageTemp: 'Refrigeracion',
    isActive: true,
    isDiscontinued: false,
    customAttributes: {},
  },

  // More Especias y Aromáticos
  {
    id: 'jengibre-004',
    createdAt: new Date('2024-11-04T01:34:12.149Z'),
    updatedAt: new Date('2024-11-04T01:51:12.733Z'),
    name: 'Jengibre Molido',
    description: 'Jengibre en polvo',
    category: 'Especias y Aromáticos',
    usedInRecipes: [],
    isResaleProduct: false,
    costPerUnit: 85,
    currency: 'COP',
    currentStock: 5,
    unit: 'g',
    suppliers: [{
      name: 'Especias Orientales',
      contact: '3155484859',
      address: 'Calle 78 #90-12',
    }],
    storageTemp: 'Ambiente',
    isActive: true,
    isDiscontinued: false,
    customAttributes: {},
  },
];

module.exports = additionalIngredients;
