const recipeTestData = {
  recipes: [
    // Basic Bread Recipe
    {
      id: "pan-frances-001",
      name: "Pan Francés",
      description: "Pan francés tradicional con corteza crujiente y miga suave",
      category: "Panadería",
      type: "Pan",
      version: 1,
      ingredients: [
        {
          ingredientId: "harina-trigo-001",
          name: "Harina de Trigo",
          quantity: 1000, // 1kg
          unit: "kg",
          notes: "Harina de fuerza para mejor desarrollo del gluten",
        },
        {
          ingredientId: "agua-001",
          name: "Agua Purificada",
          quantity: 600, // 60% hidratación
          unit: "L",
          notes: "Temperatura ambiente",
        },
        {
          ingredientId: "sal-001",
          name: "Sal Refinada",
          quantity: 20, // 2%
          unit: "kg",
          notes: "Distribuir uniformemente",
        },
        {
          ingredientId: "levadura-001",
          name: "Levadura Fresca",
          quantity: 30, // 3%
          unit: "kg",
          notes: "Disolver en agua tibia",
        },
      ],
      steps: [
        "Disolver la levadura en agua tibia",
        "Mezclar harina y sal en bowl separado",
        "Incorporar agua con levadura a los secos",
        "Amasar hasta desarrollo de gluten (10-12 min)",
        "Primera fermentación 1 hora",
        "Dividir y formar piezas",
        "Segunda fermentación 45 min",
        "Hornear a 230°C con vapor",
      ],
      preparationTime: 30,
      bakingTime: 25,
      bakingTemp: 230,
      laborCost: 10.0,
      overheadCost: 5.0,
    },

    // Sweet Pastry Recipe
    {
      id: "croissant-001",
      name: "Croissant Clásico",
      description: "Croissant tradicional francés con laminado de mantequilla",
      category: "Pastelería",
      type: "Masa Laminada",
      version: 1,
      ingredients: [
        {
          ingredientId: "harina-trigo-001",
          name: "Harina de Trigo",
          quantity: 1000,
          unit: "kg",
          notes: "Harina pastelera T45",
        },
        {
          ingredientId: "mantequilla-001",
          name: "Mantequilla",
          quantity: 500,
          unit: "kg",
          notes: "Para laminado, temperatura 18°C",
        },
        {
          ingredientId: "agua-001",
          name: "Agua Purificada",
          quantity: 500,
          unit: "L",
          notes: "Fría",
        },
        {
          ingredientId: "azucar-001",
          name: "Azúcar Blanca",
          quantity: 100,
          unit: "kg",
          notes: "Para masa",
        },
        {
          ingredientId: "sal-001",
          name: "Sal Refinada",
          quantity: 20,
          unit: "kg",
          notes: "Para masa",
        },
        {
          ingredientId: "levadura-001",
          name: "Levadura Fresca",
          quantity: 40,
          unit: "kg",
          notes: "Fresca",
        },
        {
          ingredientId: "huevos-001",
          name: "Huevos",
          quantity: 2,
          unit: "docena",
          notes: "Para masa y pintar",
        },
      ],
      steps: [
        "Mezclar ingredientes secos",
        "Incorporar líquidos gradualmente",
        "Amasar hasta desarrollo medio de gluten",
        "Refrigerar masa 2 horas",
        "Incorporar mantequilla en placa",
        "Realizar 3 vueltas simples",
        "Reposar en frío entre vueltas",
        "Formar croissants",
        "Fermentar 2-3 horas",
        "Pintar con huevo",
        "Hornear a 170°C",
      ],
      preparationTime: 180,
      bakingTime: 18,
      bakingTemp: 170,
      laborCost: 25.0,
      overheadCost: 8.0,
    },

    // Complex Cake Recipe
    {
      id: "torta-chocolate-001",
      name: "Torta de Chocolate Premium",
      description:
        "Torta de chocolate negro con ganache y decoración de frutas",
      category: "Pastelería",
      type: "Tortas",
      version: 1,
      ingredients: [
        {
          ingredientId: "harina-trigo-001",
          name: "Harina de Trigo",
          quantity: 300,
          unit: "kg",
          notes: "Tamizada",
        },
        {
          ingredientId: "chocolate-negro-001",
          name: "Chocolate Negro 70%",
          quantity: 500,
          unit: "kg",
          notes: "Picado fino",
        },
        {
          ingredientId: "mantequilla-001",
          name: "Mantequilla",
          quantity: 250,
          unit: "kg",
          notes: "Temperatura ambiente",
        },
        {
          ingredientId: "huevos-001",
          name: "Huevos",
          quantity: 1,
          unit: "docena",
          notes: "Temperatura ambiente",
        },
        {
          ingredientId: "azucar-001",
          name: "Azúcar Blanca",
          quantity: 300,
          unit: "kg",
          notes: "Para batido",
        },
        {
          ingredientId: "leche-001",
          name: "Leche Entera",
          quantity: 0.25,
          unit: "L",
          notes: "Para masa",
        },
        {
          ingredientId: "fresas-001",
          name: "Fresas",
          quantity: 200,
          unit: "kg",
          notes: "Para decoración",
        },
        {
          ingredientId: "cocoa-001",
          name: "Cocoa en Polvo",
          quantity: 50,
          unit: "kg",
          notes: "Para masa",
        },
      ],
      steps: [
        "Derretir chocolate y mantequilla a baño maría",
        "Batir huevos con azúcar hasta punto letra",
        "Incorporar mezcla de chocolate templada",
        "Agregar secos tamizados en tres partes",
        "Incorporar leche tibia",
        "Hornear en molde preparado",
        "Preparar ganache",
        "Rellenar y cubrir torta",
        "Decorar con frutas frescas",
      ],
      preparationTime: 90,
      bakingTime: 45,
      bakingTemp: 160,
      laborCost: 35.0,
      overheadCost: 15.0,
    },
  ],
};

module.exports = recipeTestData;
