const testData = {
  bakery: {
    email: "test@bakery.com",
    password: "aoeuao",
    name: "Betos Bakery",
    role: "bakery_admin",
    openingHours: {
      monday: {
        isOpen: true,
        open: "09:00",
        close: "17:00",
      },
      tuesday: {
        isOpen: true,
        open: "09:00",
        close: "17:00",
      },
      wednesday: {
        isOpen: true,
        open: "09:00",
        close: "17:00",
      },
      thursday: {
        isOpen: true,
        open: "09:00",
        close: "17:00",
      },
      friday: {
        isOpen: true,
        open: "09:00",
        close: "17:00",
      },
      saturday: {
        isOpen: true,
        open: "09:00",
        close: "17:00",
      },
      sunday: {
        isOpen: false,
        open: "",
        close: "",
      },
    },
  socialMedia: {
    facebook: "https://facebook.com/a",
    instagram: "https://instagram.com/a",
    tiktok: "https://tiktok.com/a",
    youtube: "https://youtube.com/a",
    twitter: "https://twitter.com/a",
    pinterest: "https://pinterest.com/a",
  }},
  ingredients: [
    // Harinas y Almidones
    {
      id: "harina-trigo-001",
      name: "Harina de Trigo",
      unit: "kg",
      costPerUnit: 2.5,
      allergens: ["gluten"],
      category: "Harinas y Almidones",
      minimumStock: 10,
      currentStock: 50,
      suppliers: [],
      storageTemp: "Ambiente",
    },
    {
      id: "almidon-maiz-001",
      name: "Almidón de Maíz",
      unit: "kg",
      costPerUnit: 3.0,
      allergens: [],
      category: "Harinas y Almidones",
      minimumStock: 5,
      currentStock: 25,
      suppliers: [],
      storageTemp: "Ambiente",
    },

    // Líquidos Base
    {
      id: "agua-001",
      name: "Agua Purificada",
      unit: "L",
      costPerUnit: 1.0,
      allergens: [],
      category: "Líquidos Base",
      minimumStock: 20,
      currentStock: 100,
      suppliers: [],
      storageTemp: "Ambiente",
    },
    {
      id: "leche-001",
      name: "Leche Entera",
      unit: "L",
      costPerUnit: 2.5,
      allergens: ["lactosa"],
      category: "Líquidos Base",
      minimumStock: 10,
      currentStock: 40,
      suppliers: [],
      storageTemp: "Refrigeracion",
    },

    // Sazonadores Básicos
    {
      id: "sal-001",
      name: "Sal Refinada",
      unit: "kg",
      costPerUnit: 1.5,
      allergens: [],
      category: "Sazonadores Básicos",
      minimumStock: 5,
      currentStock: 25,
      suppliers: [],
      storageTemp: "Ambiente",
    },
    {
      id: "azucar-001",
      name: "Azúcar Blanca",
      unit: "kg",
      costPerUnit: 2.0,
      allergens: [],
      category: "Sazonadores Básicos",
      minimumStock: 10,
      currentStock: 50,
      suppliers: [],
      storageTemp: "Ambiente",
    },

    // Fermentos
    {
      id: "levadura-001",
      name: "Levadura Fresca",
      unit: "kg",
      costPerUnit: 8.0,
      allergens: [],
      category: "Fermentos",
      minimumStock: 2,
      currentStock: 10,
      suppliers: [],
      storageTemp: "Refrigeracion",
    },
    {
      id: "levadura-seca-001",
      name: "Levadura Seca",
      unit: "kg",
      costPerUnit: 12.0,
      allergens: [],
      category: "Fermentos",
      minimumStock: 1,
      currentStock: 5,
      suppliers: [],
      storageTemp: "Ambiente",
    },

    // Lácteos y Proteínas
    {
      id: "huevos-001",
      name: "Huevos",
      unit: "docena",
      costPerUnit: 4.0,
      allergens: ["huevo"],
      category: "Lácteos y Proteínas",
      minimumStock: 10,
      currentStock: 30,
      suppliers: [],
      storageTemp: "Refrigeracion",
    },
    {
      id: "mantequilla-001",
      name: "Mantequilla",
      unit: "kg",
      costPerUnit: 8.0,
      allergens: ["lactosa"],
      category: "Lácteos y Proteínas",
      minimumStock: 5,
      currentStock: 20,
      suppliers: [],
      storageTemp: "Refrigeracion",
    },

    // Semillas y Granos
    {
      id: "semillas-sesamo-001",
      name: "Semillas de Sésamo",
      unit: "kg",
      costPerUnit: 10.0,
      allergens: ["sésamo"],
      category: "Semillas y Granos",
      minimumStock: 2,
      currentStock: 10,
      suppliers: [],
      storageTemp: "Ambiente",
    },
    {
      id: "nueces-001",
      name: "Nueces",
      unit: "kg",
      costPerUnit: 15.0,
      allergens: ["frutos secos"],
      category: "Semillas y Granos",
      minimumStock: 3,
      currentStock: 15,
      suppliers: [],
      storageTemp: "Ambiente",
    },

    // Frutas y Vegetales
    {
      id: "manzanas-001",
      name: "Manzanas",
      unit: "kg",
      costPerUnit: 3.0,
      allergens: [],
      category: "Frutas y Vegetales",
      minimumStock: 5,
      currentStock: 20,
      suppliers: [],
      storageTemp: "Refrigeracion",
    },
    {
      id: "fresas-001",
      name: "Fresas",
      unit: "kg",
      costPerUnit: 6.0,
      allergens: [],
      category: "Frutas y Vegetales",
      minimumStock: 3,
      currentStock: 10,
      suppliers: [],
      storageTemp: "Refrigeracion",
    },

    // Especias y Aromáticos
    {
      id: "canela-001",
      name: "Canela en Polvo",
      unit: "kg",
      costPerUnit: 20.0,
      allergens: [],
      category: "Especias y Aromáticos",
      minimumStock: 1,
      currentStock: 5,
      suppliers: [],
      storageTemp: "Ambiente",
    },
    {
      id: "vainilla-001",
      name: "Extracto de Vainilla",
      unit: "L",
      costPerUnit: 25.0,
      allergens: [],
      category: "Especias y Aromáticos",
      minimumStock: 1,
      currentStock: 3,
      suppliers: [],
      storageTemp: "Ambiente",
    },

    // Chocolates y Cocoa
    {
      id: "chocolate-negro-001",
      name: "Chocolate Negro 70%",
      unit: "kg",
      costPerUnit: 18.0,
      allergens: ["soya"],
      category: "Chocolates y Cocoa",
      minimumStock: 5,
      currentStock: 20,
      suppliers: [],
      storageTemp: "Ambiente",
    },
    {
      id: "cocoa-001",
      name: "Cocoa en Polvo",
      unit: "kg",
      costPerUnit: 12.0,
      allergens: [],
      category: "Chocolates y Cocoa",
      minimumStock: 3,
      currentStock: 15,
      suppliers: [],
      storageTemp: "Ambiente",
    },

    // Additional ingredients with different units
    {
      id: "colorante-001",
      name: "Colorante Alimentario",
      unit: "ml",
      costPerUnit: 0.5,
      allergens: [],
      category: "Especias y Aromáticos",
      minimumStock: 500,
      currentStock: 2000,
      suppliers: [],
      storageTemp: "Ambiente",
    },
    {
      id: "decoraciones-001",
      name: "Decoraciones Surtidas",
      unit: "paquete",
      costPerUnit: 5.0,
      allergens: [],
      category: "Especias y Aromáticos",
      minimumStock: 10,
      currentStock: 30,
      suppliers: [],
      storageTemp: "Ambiente",
    },

    // More ingredients with Congelacion storage
    {
      id: "pulpa-fruta-001",
      name: "Pulpa de Frutas Congelada",
      unit: "kg",
      costPerUnit: 7.0,
      allergens: [],
      category: "Frutas y Vegetales",
      minimumStock: 5,
      currentStock: 20,
      suppliers: [],
      storageTemp: "Congelacion",
    },
    {
      id: "masa-hojaldre-001",
      name: "Masa de Hojaldre",
      unit: "kg",
      costPerUnit: 9.0,
      allergens: ["gluten"],
      category: "Harinas y Almidones",
      minimumStock: 5,
      currentStock: 15,
      suppliers: [],
      storageTemp: "Congelacion",
    },
  ],
};

module.exports = testData;
