const additionalIngredients = require('./additionalIngredients');
const additionalRecipes = require('./additionalRecipes');

const testData = {
  bakery: {
    email: 'test@bakery.com',
    password: 'aoeuao',
    name: 'Betos Bakery',
    role: 'bakery_admin',
    openingHours: {
      monday: {
        isOpen: true,
        open: '09:00',
        close: '17:00',
      },
      tuesday: {
        isOpen: true,
        open: '09:00',
        close: '17:00',
      },
      wednesday: {
        isOpen: true,
        open: '09:00',
        close: '17:00',
      },
      thursday: {
        isOpen: true,
        open: '09:00',
        close: '17:00',
      },
      friday: {
        isOpen: true,
        open: '09:00',
        close: '17:00',
      },
      saturday: {
        isOpen: true,
        open: '09:00',
        close: '17:00',
      },
      sunday: {
        isOpen: false,
        open: '',
        close: '',
      },
    },
    socialMedia: {
      facebook: 'https://facebook.com/a',
      instagram: 'https://instagram.com/a',
      tiktok: 'https://tiktok.com/a',
      youtube: 'https://youtube.com/a',
      twitter: 'https://twitter.com/a',
      pinterest: 'https://pinterest.com/a',
    } },
  ingredients: [
    ...additionalIngredients,
    // Harinas y Almidones
    {
      id: 'harina-integral-002',
      createdAt: new Date('2024-11-04T01:34:12.149Z'),
      updatedAt: new Date('2024-11-04T01:51:12.733Z'),
      name: 'Harina Integral',
      description: 'Harina de trigo integral rica en fibra',
      category: 'Harinas y Almidones',
      usedInRecipes: [], // Will be populated based on recipes
      isResaleProduct: false,
      costPerUnit: 14,
      currency: 'COP',
      currentStock: 25,
      unit: 'g',
      suppliers: [
        {
          name: 'Molinos del Norte',
          contact: '3155484849',
          address: 'Calle 123 #45-67',
        },
      ],
      storageTemp: 'Ambiente',
      isActive: true,
      isDiscontinued: false,
      customAttributes: {},
    },
    {
      id: 'harina-centeno-003',
      createdAt: new Date('2024-11-04T01:34:12.149Z'),
      updatedAt: new Date('2024-11-04T01:51:12.733Z'),
      name: 'Harina de Centeno',
      description: 'Harina de centeno para panes especiales',
      category: 'Harinas y Almidones',
      usedInRecipes: [],
      isResaleProduct: false,
      costPerUnit: 16,
      currency: 'COP',
      currentStock: 15,
      unit: 'g',
      suppliers: [
        {
          name: 'Granos Premium',
          contact: '3155484850',
          address: 'Av Principal #78-90',
        },
      ],
      storageTemp: 'Ambiente',
      isActive: true,
      isDiscontinued: false,
      customAttributes: {},
    },

    // Lácteos y Proteínas
    {
      id: 'leche-entera-002',
      createdAt: new Date('2024-11-04T01:34:12.149Z'),
      updatedAt: new Date('2024-11-04T01:51:12.733Z'),
      name: 'Leche Entera',
      description: 'Leche entera pasteurizada',
      category: 'Lácteos y Proteínas',
      usedInRecipes: [],
      isResaleProduct: false,
      costPerUnit: 3,
      currency: 'COP',
      currentStock: 50,
      unit: 'ml',
      suppliers: [
        {
          name: 'Lácteos del Valle',
          contact: '3155484851',
          address: 'Carrera 34 #56-78',
        },
      ],
      storageTemp: 'Refrigeracion',
      isActive: true,
      isDiscontinued: false,
      customAttributes: {},
    },
    {
      id: 'mantequilla-003',
      createdAt: new Date('2024-11-04T01:34:12.149Z'),
      updatedAt: new Date('2024-11-04T01:51:12.733Z'),
      name: 'Mantequilla Sin Sal',
      description: 'Mantequilla sin sal para repostería',
      category: 'Lácteos y Proteínas',
      usedInRecipes: [],
      isResaleProduct: false,
      costPerUnit: 18,
      currency: 'COP',
      currentStock: 20,
      unit: 'g',
      suppliers: [
        {
          name: 'Lácteos Premium',
          contact: '3155484852',
          address: 'Calle 90 #12-34',
        },
      ],
      storageTemp: 'Refrigeracion',
      isActive: true,
      isDiscontinued: false,
      customAttributes: {},
    },

    // Especias y Aromáticos
    {
      id: 'vainilla-002',
      createdAt: new Date('2024-11-04T01:34:12.149Z'),
      updatedAt: new Date('2024-11-04T01:51:12.733Z'),
      name: 'Extracto de Vainilla',
      description: 'Extracto natural de vainilla',
      category: 'Especias y Aromáticos',
      usedInRecipes: [],
      isResaleProduct: false,
      costPerUnit: 45,
      currency: 'COP',
      currentStock: 10,
      unit: 'ml',
      suppliers: [
        {
          name: 'Esencias del Mundo',
          contact: '3155484853',
          address: 'Av Central #45-67',
        },
      ],
      storageTemp: 'Ambiente',
      isActive: true,
      isDiscontinued: false,
      customAttributes: {},
    },
    {
      id: 'cardamomo-003',
      createdAt: new Date('2024-11-04T01:34:12.149Z'),
      updatedAt: new Date('2024-11-04T01:51:12.733Z'),
      name: 'Cardamomo Molido',
      description: 'Cardamomo molido para especiados',
      category: 'Especias y Aromáticos',
      usedInRecipes: [],
      isResaleProduct: false,
      costPerUnit: 120,
      currency: 'COP',
      currentStock: 5,
      unit: 'g',
      suppliers: [
        {
          name: 'Especias Orientales',
          contact: '3155484854',
          address: 'Calle 67 #89-12',
        },
      ],
      storageTemp: 'Ambiente',
      isActive: true,
      isDiscontinued: false,
      customAttributes: {},
    },

    // Frutas y Vegetales
    {
      id: 'arandanos-002',
      createdAt: new Date('2024-11-04T01:34:12.149Z'),
      updatedAt: new Date('2024-11-04T01:51:12.733Z'),
      name: 'Arándanos Deshidratados',
      description: 'Arándanos deshidratados sin azúcar',
      category: 'Frutas y Vegetales',
      usedInRecipes: [],
      isResaleProduct: false,
      costPerUnit: 45,
      currency: 'COP',
      currentStock: 15,
      unit: 'g',
      suppliers: [
        {
          name: 'Frutos Secos del Valle',
          contact: '3155484855',
          address: 'Carrera 78 #90-12',
        },
      ],
      storageTemp: 'Ambiente',
      isActive: true,
      isDiscontinued: false,
      customAttributes: {},
    },
  ],
  recipes: [
    ...additionalRecipes,
    {
      id: 'pan-integral-especial-001',
      createdAt: new Date('2024-11-04T01:51:12.733Z'),
      updatedAt: new Date('2024-11-04T01:51:45.922Z'),
      name: 'Pan Integral Especial',
      description: 'Pan integral con semillas y especias',
      version: 1,
      ingredients: [
        {
          ingredientId: 'harina-integral-002',
          name: 'Harina Integral',
          quantity: 500,
          unit: 'g',
          costPerUnit: 14,
          notes: 'Tamizada',
        },
        {
          ingredientId: 'cardamomo-003',
          name: 'Cardamomo Molido',
          quantity: 5,
          unit: 'g',
          costPerUnit: 120,
          notes: 'Al gusto',
        },
      ],
      steps: [
        'Mezclar harina integral con cardamomo',
        'Agregar agua gradualmente mientras se amasa',
        'Dejar reposar por 1 hora',
        'Formar el pan y hornear a 180°C por 35 minutos',
      ],
      preparationTime: 75,
      bakingTime: 35,
      isActive: true,
      notes: 'Mantener la masa con 70% de hidratación',
    },
    {
      id: 'galletas-arandanos-001',
      createdAt: new Date('2024-11-04T01:51:12.733Z'),
      updatedAt: new Date('2024-11-04T01:51:45.922Z'),
      name: 'Galletas de Arándanos',
      description: 'Galletas suaves con arándanos deshidratados',
      version: 1,
      ingredients: [
        {
          ingredientId: 'harina-trigo-001',
          name: 'Harina de Trigo',
          quantity: 250,
          unit: 'g',
          costPerUnit: 12,
          notes: 'Tamizada',
        },
        {
          ingredientId: 'mantequilla-003',
          name: 'Mantequilla Sin Sal',
          quantity: 150,
          unit: 'g',
          costPerUnit: 18,
          notes: 'Temperatura ambiente',
        },
        {
          ingredientId: 'arandanos-002',
          name: 'Arándanos Deshidratados',
          quantity: 100,
          unit: 'g',
          costPerUnit: 45,
          notes: 'Picados gruesamente',
        },
        {
          ingredientId: 'vainilla-002',
          name: 'Extracto de Vainilla',
          quantity: 5,
          unit: 'ml',
          costPerUnit: 45,
          notes: 'Al gusto',
        },
      ],
      steps: [
        'Cremar mantequilla',
        'Agregar extracto de vainilla',
        'Incorporar harina gradualmente',
        'Agregar arándanos',
        'Formar galletas y hornear a 170°C por 15 minutos',
      ],
      preparationTime: 30,
      bakingTime: 15,
      isActive: true,
      notes: 'Las galletas deben quedar doradas en los bordes',
    },
  ],
};

module.exports = testData;
